### ISSUE TITLE
Dźwięk szumu radiowego

### ISSUE THREAD

**Issue by Pastew** [Pastew/krakjam2017#6]
Znaleźć dźwięk szumu radiowego - jak audycja nie jest wybrana ale jest włączone nadawanie

**Comment by Sieciesznik** [comment]
nie wiem czy to takie ważne, w praktyce przy aktualnej mechanice coś takiego może mieć miejsce tylko na początku, bo potem zawsze jakaś audycja jest wybrana, chyba że zmienimy coś w mechanice
